### ISSUE TITLE
Directory API is Down?

### ISSUE THREAD

**Issue by DerekTBrown** [ScottyLabs/directory-api#3]
Can't seem to access the API right now.  Is something going on?

**Comment by bezi** [comment]
The issue should be addressed.  We experienced some downtime due to a server configuration conflict.

**Comment by DerekTBrown** [comment]
@bezi Just wanted to let you guys know that CMU A Cappella is using this for all of our auditions: 

(the Original's page for instance)
http://audition.cmuacappella.org/originals/

Thanks for all of your hard work!
